export const CSS_HANDLES = [
  'pkfWrap',
  'pkfPanel',
  'pkfPanelSuccess',
  'pkfView',
  'pkfViewConsult',
  'pkfViewResult',
  'pkfConsultBody',
  'pkfDescription',
  'pkfErrorMsg',
  'pkfFormControls',
  'pkfInputWrapper',
  'pkfInput',
  'pkfInputError',
  'pkfInputErrorText',
  'pkfButton',
  'pkfButtonGhost',
  'pkfImgArea',
  'pkfPokemonImg',
  'pkfFields',
  'pkfCardField',
  'pkfCardLabel',
  'pkfCardValue',
  'pkfSkeleton',
  'pkfSkeletonImg',
  'pkfSkeletonField',
  'pkfSkeletonShort',
  'pkfSpinner',
  'pkfWarning',
] as const

export const TYPE_COLORS: Record<string, string> = {
  fire: '#FF6B35', water: '#4A90D9', grass: '#56C271', electric: '#F9D526',
  psychic: '#FF6FA0', ice: '#74D0F1', dragon: '#6A5ACD', dark: '#3D2B4E',
  fairy: '#FFB6C1', fighting: '#C0392B', poison: '#9B59B6', ground: '#D4A843',
  rock: '#8B7355', ghost: '#5D478B', steel: '#7F8C8D', bug: '#8BC34A',
  flying: '#81D4FA', normal: '#A8A878',
}
